### ISSUE TITLE
Use csaf-validator-lib

### ISSUE THREAD

**Issue by tschmidtb51** [ctron/csaf-walker#14]
The OASIS Open CSAF TC provides an implementation of a [CSAF full validator](https://docs.oasis-open.org/csaf/csaf/v2.0/os/csaf-v2.0-os.html#9116-conformance-clause-16-csaf-full-validator) as library ([`csaf-validator-lib`](https://github.com/secvisogram/csaf-validator-lib)) and REST service ([`csaf-validator-service`](https://github.com/secvisogram/csaf-validator-service)).

This could be used to implement all mandatory (and optional and informative) tests quickly.

**Comment by ctron** [comment]
I agree, that would be valuable. I already tried to get the actual JavaScript code run as part of the csaf-walker using `deno`. However, the tests seem to access various APIs (like network), which makes that pretty hard.

Another, quicker, alternative might be to just pass that to the HTTP endpoint. It would be less self-contained though, but I guess, still worth it.

**Comment by tschmidtb51** [comment]
One idea could be to start with the mandatory tests - as far as I remember, they do not use any network APIs...

**Comment by ctron** [comment]
IIRC I tried that, but failed (maybe that was just me). However, there are two people not looking into this with additional time and ideas (@bxf12315 and @danbev).

One idea that also come up was to compile the JavaScript bits to WASM. And use a WASM interpreter to run that code (vs setting up a deno embedded instance). @danbev has some experience with that.

**Comment by ctron** [comment]
I was able to take another look at this an claim success! (Thanks to a good pointer from @bxf12315).

The following out is the Rust struct for reporting validation errors, filled with the validation results from the JavaScript code. It's easily possible to take the `Csaf` struct, and send that to the JS side, capturing the results and translating that into the Rust structs again.

I still need to wire this up internally. But that should only be a bit of plumbing. Maybe I'll find some time for this tomorrow. I am pretty sure we need to improve the validation a bit on the Rust side of things. As right now, there are only "errors", which we render as warnings later on. But hey, one step at a time.

```
[2024-02-15T17:51:52Z INFO  csaf_walker::verification::check::csaf_validator_lib::test] Result: [
        "csaf_2_0: must NOT have fewer than 1 characters",
        "csaf_2_0: must NOT have fewer than 1 characters",
        "csaf_2_0: must NOT have fewer than 1 characters",
        "csaf_2_0: must match pattern \"^[\\S](.*[\\S])?$\"",
        "csaf_2_0: must NOT have fewer than 1 items",
        "csaf_2_0: must match pattern \"^(0|[1-9][0-9]*)$|^((0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?)$\"",
        "csaf_2_0_strict: must NOT have fewer than 1 characters",
        "csaf_2_0_strict: must NOT have fewer than 1 characters",
        "csaf_2_0_strict: must NOT have fewer than 1 characters",
        "csaf_2_0_strict: must match pattern \"^[\\S](.*[\\S])?$\"",
        "csaf_2_0_strict: must NOT have fewer than 1 items",
        "csaf_2_0_strict: must match pattern \"^(0|[1-9][0-9]*)$|^((0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?)$\"",
    ]
```
